services:
  - type: web
    name: wikihunt-bot
    env: python
    plan: free
    pythonVersion: "3.11"
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn sbert-server:app --host 0.0.0.0 --port 8000"
